### ISSUE TITLE
"blackCauldron7/surround.nvim" is no longer available

### ISSUE THREAD

**Issue by abdes** [ChristianChiarulli/nvim#10]
"blackCauldron7/surround.nvim" is no longer available (requests produces a 404, and user no longer exists on GitHub).

**Comment by kevinm6** [comment]
Replace it with its fork.
[Mephistophiles/surround.nvim](https://github.com/Mephistophiles/surround.nvim)

`use "Mephistophiles/surround.nvim"`

**Comment by ChristianChiarulli** [comment]
https://github.com/ChristianChiarulli/nvim/commit/f0b69716a2a588b2afb8530b538eb62bfb056a53
