### ISSUE TITLE
Uninstalling coc-java and coc-java-debug does not work

### ISSUE THREAD

**Issue by Hamzailer** [ChristianChiarulli/nvim#104]
Whenever I try to uninstall coc-java and coc-java-debug it automatically reinstalls it

**Comment by ChristianChiarulli** [comment]
yea there's a file in `plug-config/coc/coc-extensions.vim`. This will automatically reinstall all of my plugins. You can delete the ones you don't want.

**Comment by Hamzailer** [comment]
Ah thanks
