### ISSUE TITLE
error Server languageserver.lua failed to start

### ISSUE THREAD

**Issue by ogfunkycold** [ChristianChiarulli/nvim#105]
hi Chris,
after clone and install 'nvim' for first time from your repo and when I've got the error

[coc.nvim]  Server languageserver.lua failed to start:  Launching server "languageserver.lua" using command /home/chris/.luambenvs/neovim4/bin/lua.lsp failed"

In your coc-settings I found the definition of languageserver 
  
  "languageserver": {
    "lua": {
      "command": "/home/chris/.luambenvs/neovim4/bin/lua-lsp",
      "filetypes": ["lua"],
      "trace.server": "verbose"
    }
  },

So the error is that doesn't exist /home/chris on my arch.. but I'dont know how fixed!     In your Blog I can't found any pre-install about the languageserver.

Can you guide me in oren to fix it?

Best Regards

PD:  btw, it's excelent your nvim implementation...

**Comment by ChristianChiarulli** [comment]
I was defining a custom lang server for lua development. I hardcoded my name into it. Should be fixed now. Just pull master.

Thanks for the support

**Comment by ogfunkycold** [comment]
Thanks Christian!!!  I follow your nvim repo since your first videos.. I am the grateful...
