### ISSUE TITLE
Can not move between splitted window

### ISSUE THREAD

**Issue by ochilliam** [ChristianChiarulli/nvim#106]
Either vertically or horizontally. i did disable the default cmd+h but didn't work. btw any progress on vim-surround issue? really need this. thanks guys for this awesome config. 

Device: mac Mojave version 10.14.2

**Comment by ChristianChiarulli** [comment]
I don't think that cmd key works for vim. No progress on surround yet. Which key is kinda messing up my timeout, hopefully I find a fix soon but it's not a priority currently.
