### ISSUE TITLE
lua interpreter

### ISSUE THREAD

**Issue by Blackbear7891** [ChristianChiarulli/nvim#109]
Se ha detectado un error al procesar function <SNR>3_install[1]..<SNR>3_update_impl:
línea   55
E970: Failed to initialize lua interpreter
Pulse INTRO o escriba una orden para continuar
E970: Failed to initialize lua interpreter
Pulse INTRO o escriba una orden para continuar
E970: Failed to initialize lua interpreter
Pulse INTRO o escriba una orden para continuarVim: Finished.

**Comment by ChristianChiarulli** [comment]
Not sure what the issue is here sorry.
