### ISSUE TITLE
Surround key maps not working 

### ISSUE THREAD

**Issue by rodriguezmarting** [ChristianChiarulli/nvim#11]
After a clean re install none of the surround keybindings are working.
Tried to find out why without success.

**Comment by ChristianChiarulli** [comment]
I haven't fully configured surround yet, I'll probably do this in a future video so I'm not surprised it doesn't work.

**Comment by papeloto** [comment]
Any clue of why this could happen? At first, I thought that the mappings of `sneak` and `surrounding` had a conflict but even disabling `sneak` it doesn't work.

I think I might try luck with [vim-sandwich](https://github.com/machakann/vim-sandwich) after reading this article (https://joereynoldsaudio.com/2020/01/22/vim-sandwich-is-better-than-surround.html)

**Comment by papeloto** [comment]
Okey I just figured out, it has to do with the `timeoutlen` if you hit them very quickly or increase the length it works :facepalm:

**Comment by rodriguezmarting** [comment]
Thanks @papeloto I can confirmed both vim-commentary and vim-surround were failing for the  `timeoutlen`.
For anyone else who wants those plugins to be usable change `timeoutlen` in `general/settings.vim`. It is at 100ms by @ChristianChiarulli, change it to whatever feel comfortable to you. I use it at 1000ms (default).
Will close the issue.

**Comment by roberto-civitas** [comment]
It doesnt work for me even by increasing the timeout, when I try to surround something the "marks" popup shows up when I press the quote key. Any suggestions would be appreciated.
