### ISSUE TITLE
File Icons not showing 

### ISSUE THREAD

**Issue by MoSchaub** [ChristianChiarulli/nvim#112]
I am iterm2 Build 3.4.4 on mac os 11. 0. 2, I am running the newest neovim compiled from source and I pasted the install command into my terminal. Everything besides the icons seams to be working fine but I cant see the file icons. They are just question marks in boxes. (See the image below)
![image](https://user-images.githubusercontent.com/54505431/108118231-5352a180-709e-11eb-8f5b-527cf80a10a3.png)

**Comment by MoSchaub** [comment]
I fixed it by setting SouceCodePro Nerd Font as my Terminal Font https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/SourceCodePro.zip

**Comment by Blacksheepi** [comment]
I have the same problem, could you be more specific how to fix
