### ISSUE TITLE
treesitter// nvim-treesitter issues

### ISSUE THREAD

**Issue by heresy0-0y** [ChristianChiarulli/nvim#115]
the in terminal error i get just running nvim after a fresh brew install and running your bash command:::
using iterm2, oh my zsh, homebrew, on macos bigSur

`Error detected while processing /Users/hera/.config/nvim/init.vim:
line   37:
E5113: Error while calling lua chunk: ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:2: module 'vim.treesitter.query' not found:
        no field package.preload['vim.treesitter.query']
        no file '/Users/hera/.config/nvim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-commentary/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-commentary/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-speeddating/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-speeddating/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-radical/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-radical/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-repeat/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-repeat/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/quick-scope/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/quick-scope/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-context-commentstring/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-context-commentstring/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-easymotion/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-easymotion/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-surround/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-surround/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-rooter/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-rooter/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-sleuth/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-sleuth/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/nvim-treesitter/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/nvim-treesitter/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/playground/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/playground/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/nvim-web-devicons/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/nvim-web-devicons/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-devicons/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-devicons/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/auto-pairs/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/auto-pairs/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-closetag/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-closetag/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/nvcode-color-schemes.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/nvcode-color-schemes.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/coc.nvim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/coc.nvim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/coc.nvim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/galaxyline.nvim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/galaxyline.nvim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/rnvimr/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/rnvimr/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/fzf/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/fzf/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/fzf-preview.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/fzf-preview.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/fzf.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/fzf.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-gitgutter/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-gitgutter/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-fugitive/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-fugitive/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-rhubarb/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-rhubarb/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/gv.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/gv.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/git-messenger.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/git-messenger.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-floaterm/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-floaterm/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-startify/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-startify/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vista.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vista.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-which-key/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-which-key/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/goyo.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/goyo.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-snippets/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/vim-snippets/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/emmet-vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/emmet-vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/codi.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/codi.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/barbar.nvim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/barbar.nvim/lua/vim/treesitter/query/init.lua'
         no file '/Users/hera/.config/nvim/autoload/plugged/barbar.nvim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/undotree/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/undotree/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/far.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/far.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/tagalong.vim/lua/vim/treesitter/query.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/tagalong.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/hera/.config/nvim/autoload/plugged/bracey.vim/lua/vim/treesitter/query.lua'
Error detected while processing /Users/hera/.config/nvim/autoload/plugged/nvim-treesitter/plugin/nvim-treesitter.vim:
line   15:
E5105: Error while calling lua chunk: ...autoload/plugged/nvim-treesitter/lua/nvim-treesitter.lua:2: nvim-treesitter requires a more recent Neovim nightly version!
Error detected while processing /Users/hera/.config/nvim/autoload/plugged/playground/plugin/nvim-treesitter-playground.vim:
line    3:
E5105: Error while calling lua chunk: ...ad/plugged/playground/lua/nvim-treesitter-playground.lua:5: loop or previous error loading module 'nvim-treesitter'
Error detected while processing /Users/hera/.config/nvim/autoload/plugged/barbar.nvim/plugin/bufferline.vim:
line  237:
E5108: Error while calling lua chunk for luaeval(): ...im/autoload/plugged/barbar.nvim/lua/bufferline/utils.lua:7: attempt to index field 'fn' (a nil value)
Error detected while processing BufWinEnter Autocommands for "*":
E5105: Error while calling lua chunk: /Users/hera/.config/nvim/lua/nvcodeline.lua:22: attempt to index field 'fn' (a nil value)
Error detected while processing BufEnter Autocommands for "*":
E5105: Error while calling lua chunk: /Users/hera/.config/nvim/lua/nvcodeline.lua:22: attempt to index field 'fn' (a nil value)
Error detected while processing FileType Autocommands for "*":
E5105: Error while calling lua chunk: /Users/hera/.config/nvim/lua/nvcodeline.lua:22: attempt to index field 'fn' (a nil value)`

running checkhealth

`health#nvim_treesitter#check
    3 ========================================================================
    4   - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    5     function health#check[21]..health#nvim_treesitter#check, line 1
    6     Vim(lua):E5105: Error while calling lua chunk: ...d/plugged/nvim-treesitter/lua/nvim-treesitter/health.lua:4: loop or previous error loading module 'nvim-              treesitter.query'
    7
    8 health#coc#check
    9 ========================================================================
   10   - OK: Environment check passed
   11
   12   - OK: Javascript bundle build/index.js found
   13   - OK: Service started
   14
   15 health#rnvimr#check
   16 ========================================================================
   17 ## OS
   18   - OK: Name: Mac
   19
   20 ## Ranger
   21   - ERROR: Ranger not Found
   22
   23 ## Pynvim
   24   - OK: Version: 0.4.2
   25
   26 ## Ueberzug (optional)
   27   - INFO: Ueberzug is not support for Mac
   28
   29 ## RPC
   30   - ERROR: Vim(sleep):Error executing vim.schedule lua callback: /Users/hera/.config/nvim/lua/nvcodeline.lua:22: attempt to index field 'fn' (a nil value)
   31
   32 health#gitmessenger#check
   33 ========================================================================
   34   - OK: +job is available to execute Git command
   35   - OK: Git command `git` is available: git version 2.30.1
   36   - OK: Floating window is available for popup window
37
   38 health#floaterm#check
   39 ========================================================================
   40 ## common
   41   - INFO: Platform: macos
   42   - INFO: Nvim: NVIM v0.4.4
   43   - INFO: Plugin: c66412d
   44
   45
   46 ## terminal
   47   - OK: Terminal emulator is available
   48
   49 ## floating
   50   - OK: Floating window is available
   51
   52 health#mkdp#check
   53 ========================================================================
   54   - INFO: Platform: macos
   55   - INFO: Nvim Version: NVIM v0.4.4
   56   - INFO: Node version: v15.9.0
   57
   58   - INFO: Script: /Users/hera/.config/nvim/autoload/plugged/markdown-preview.nvim/app/server.js
   59   - INFO: Script exists: 1
   60   - OK: Using node
   61
   62 health#nvim#check
   63 ========================================================================
   64 ## Configuration
   65   - OK: no issues found
   66
   67 ## Performance
   68   - OK: Build type: Release
   69
   70 ## Remote Plugins
   71   - OK: Up to date72
   73 ## terminal
   74   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
   75   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   76   - INFO: $TERM_PROGRAM='iTerm.app'
   77   - INFO: $COLORTERM='truecolor'
   78
   79 health#provider#check
   80 ========================================================================
   81 ## Clipboard (optional)
   82   - OK: Clipboard tool found: pbcopy
   83
   84 ## Python 2 provider (optional)
   85   - WARNING: No Python executable found that can import neovim. Using the first available executable for diagnostics.
   86   - ERROR: Python provider error:
   87     - ADVICE:
   88       - provider/pythonx: Could not load Python 2:
   89           /usr/bin/python2 does not have the "neovim" module. :help provider-python
   90           /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
   91           python2.6 not found in search path or not executable.
   92           /usr/bin/python does not have the "neovim" module. :help provider-python
   93   - INFO: Executable: Not found
   94
   95 ## Python 3 provider (optional)
   96   - INFO: g:python3_host_prog is not set.  Searching for python3 in the environment.
   97   - INFO: Multiple python3 executables found.  Set g:python3_host_prog to avoid surprises.
   98   - INFO: Executable: /usr/local/bin/python3
   99   - INFO: Other python executable: /usr/bin/python3
  100   - INFO: Python version: 3.9.2
  101   - INFO: pynvim version: 0.4.2
  102   - OK: Latest pynvim is installed.
  103
  104 ## Ruby provider (optional)
  105   - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
  106   - WARNING: neovim-ruby-host not found.
  107     - ADVICE:
108       - Run gem install neovim to ensure the neovim RubyGem is installed.
  109       - Run gem environment to ensure the gem bin directory is in $PATH.
  110       - If you are using rvm/rbenv/chruby, try "rehashing".
  111       - See :help g:ruby_host_prog for non-standard gem installations.
  112
  113 ## Node.js provider (optional)
  114   - INFO: Node.js: v15.9.0
  115   - INFO: Neovim node.js host: /Users/hera/.nvm/versions/node/v15.9.0/lib/node_modules/neovim/bin/cli.js
  116   - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
  117`
**just a note: running :UpdateRemotePlugins also throws an error

another error just exiting vim

`Error detected while processing function bufferline#update[1]..bufferline#render:
line    1:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: loop or previous error loading module 'bufferline.render'
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: loop or previous error loading module 'bufferline.render'
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: loop or previous error loading module 'bufferline.render'
Error detected while processing BufEnter Autocommands for "*":
E5105: Error while calling lua chunk: /Users/hera/.config/nvim/lua/nvcodeline.lua:22: attempt to index field 'fn' (a nil value)
Error detected while processing function bufferline#update[1]..bufferline#render:
line    1:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: loop or previous error loading module 'bufferline.render'
Error detected while processing BufWinEnter Autocommands for "*":
E5105: Error while calling lua chunk: /Users/hera/.config/nvim/lua/nvcodeline.lua:22: attempt to index field 'fn' (a nil value)
Error detected while processing function bufferline#update[1]..bufferline#render:
line    1:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: loop or previous error loading module 'bufferline.render'`

**Comment by jordisantamaria** [comment]
are you using nvim 0.5? I had a similar error when was using the stable version of nvim 0.4

**Comment by heresy0-0y** [comment]
bloop !~ yupyupyup, was using 0.4.4 (stable)

for folks that run into the same later : 
#### be sure to run 'brew uninstall neovim' if you already have neovim installed
`brew install --HEAD neovim`
