### ISSUE TITLE
The plugin "blackCauldron7/surround.nvim" no longer exists

### ISSUE THREAD

**Issue by nulloneguy** [ChristianChiarulli/nvim#12]
`github.com/blackCauldron7/surround.nvim`
author deleted the repository

**Comment by ChristianChiarulli** [comment]
yea I really should update to the popular fork that's out there somewhere

**Comment by ChristianChiarulli** [comment]
https://github.com/ChristianChiarulli/nvim/commit/f0b69716a2a588b2afb8530b538eb62bfb056a53
