### ISSUE TITLE
fzf.vim errors --info=inline should be --inline-info 

### ISSUE THREAD

**Issue by mandaputtra** [ChristianChiarulli/nvim#12]
Hi, I'm from your fzf youtube tutorials, on my machine fzf will work if ~ you change

```
--info=inline 
```

to

```
--inline-info
```

**Comment by mandaputtra** [comment]
Could you try on yours? if you it work better change it to `--inline-info` since the man page also had that example.

**Comment by ChristianChiarulli** [comment]
Hmm could you maybe make a pull request for this and I'll test it out?

**Comment by mandaputtra** [comment]
There ya go #17

**Comment by ChristianChiarulli** [comment]
Thanks!
