### ISSUE TITLE
Problem using FZF in NVim

### ISSUE THREAD

**Issue by RockatanskyV8** [ChristianChiarulli/nvim#13]
I'm facing a problem in this particular line:
let $FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git/**'"

It shows this error message:

![image](https://user-images.githubusercontent.com/17436322/82106647-b622a100-96f8-11ea-8237-e50d7603d146.png)

when I comment it, it runs normally. But I'm not sure on what this line does so I'm afraid I might losing some feature that I don't know now.

**Comment by ChristianChiarulli** [comment]
Do you have ripgrep installed?

I to could be that.

**Comment by RockatanskyV8** [comment]
I just installed it. It was exactly it.

**Comment by ChristianChiarulli** [comment]
Awesome! closing

**Comment by 0xRainy** [comment]
@ChristianChiarulli sorry to revive but I have ripgrep installed and getting the same error

Running the command in my term works fine.
Running `:Rg` inside nvim also works fine

I don't think I need floatingterm plugin (I dont have it installed) but you tell me.

I'm on windows 10 using WindowsTerminal with powershell
also getting this:

``Error running ^"C:\Users\rainy\.config\nvim\autoload\plugged\fzf/bin/fzf^" --history ^"C:\Users\rainy\.local\share\fzf-history/rg^" ^"--color=bg+:242,border:0,spinner:11,hl:14,header:14,info:81,pointer:11,marker:11,prompt:11,hl+:11^" ^"--ansi^" ^"--prompt^" ^"Rg^> ^" ^"--multi^" ^"--bind^" ^"alt-a:select-all,alt-d:deselect-all^" ^"--color^" ^"hl:4,hl+:12^" --delimiter : --nth 4.. -e ^"--preview-window^" ^"right:50%%^" ^"--preview^" ^"bash /mnt/c/Users/rainy/CONFIG~1/nvim/autoload/plugged/fzf.vim/bin/preview.sh {}^" ^"--bind^" ^"?:toggle-preview^" --expect=ctrl-v,ctrl-x,ctrl-t --no-height > C:\Users\rainy\AppData\Local\Temp\nvimJudMYY\2
Error running ^"C:\Users\rainy\.config\nvim\autoload\plugged\fzf/bin/fzf^" --history ^"C:\Users\rainy\.local\share\fzf-history/FZF^" ^"--color=bg+:242,border:0,spinner:11,hl:14,header:14,info:81,pointer:11,marker:11,prompt:11,hl+:11^" ^"--multi^" ^"--prompt^" ^"C:\r\chatterino2\\^" --expect=ctrl-v,ctrl-x,ctrl-t --no-height > C:\Users\rainy\AppData\Local\Temp\nvimJudMYY\14``
