### ISSUE TITLE
Which-keys 

### ISSUE THREAD

**Issue by benbrastmckie** [ChristianChiarulli/nvim#16]
I cut and paste the which-keys.vim file you have, but noticed that the final line was giving me the following error:

![Screenshot from 2020-05-16 20-24-47](https://user-images.githubusercontent.com/64314593/82128522-a74cf480-97b3-11ea-8a3b-84c31701cf8c.png)

I commented out the line, and the error has gone away. I would be curious to know what I am missing out on. Thanks so much!

**Comment by ChristianChiarulli** [comment]
Could you post your config so I can take a look?

**Comment by benbrastmckie** [comment]
I'm still figuring out how to use github, and so couldn't find a better way to post my config files than to share my repo, which I'm sure you'll recognize is the result of cutting and pasting bits of yours. Here is the link: https://github.com/benbrastmckie/VimConfig

**Comment by ChristianChiarulli** [comment]
```call plug#begin('~/.config/nvim/autoload/plugged')

    " Better Syntax Support
"    Plug 'sheerun/vim-polyglot'
    " File Explorer
    Plug 'scrooloose/NERDTree'
    " Auto pairs for '(' '[' '{' 
    Plug 'jiangmiao/auto-pairs'
    " Themes 
    Plug 'joshdick/onedark.vim'
    " Satus Line
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    " Startup Screen
    Plug 'mhinz/vim-startify'
    Plug 'mhinz/vim-signify'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-rhubarb'
    Plug 'junegunn/gv.vim'
    Plug 'justinmk/vim-sneak'

call plug#end()```

You dont have which key installed

so either install that or remove the line sourcing which key in init.vim 

let me know if that works for you.

**Comment by benbrastmckie** [comment]
That did the trick. Thanks so much and sorry for the elementary question.
