### ISSUE TITLE
change font color

### ISSUE THREAD

**Issue by MHDFahz** [ChristianChiarulli/nvim#20]

**Comment by ChristianChiarulli** [comment]
Are you saying I should change it or that you want to change it? 

I don't understand the issue you raised.

**Comment by MHDFahz** [comment]
I am using your confg for my nvim but don't know how to change the font colour and and highlight line to underline

**Comment by ChristianChiarulli** [comment]
Checkout some other colorschemes. I think I did a video on it. If you want fine grain control of a colorscheme I recommend forking and adding in the colors you like.
