### ISSUE TITLE
Cpp Autocomplete Issue

### ISSUE THREAD

**Issue by abdiksalah** [ChristianChiarulli/nvim#23]
I do not have c++ autocomplete. 
It works python fine. I can write cpp code and run it but there is no intellisense 
Thank you,

**Comment by ChristianChiarulli** [comment]
Try `:CocInstall coc-clangd`

You just don't have the right extension installed, this should fix that.

**Comment by abdiksalah** [comment]
![example](https://user-images.githubusercontent.com/54428996/83937154-0046f180-a790-11ea-8b3f-cf2bcecc98a2.png)
Great!.
It worked well. I had to add "yarn install --frozen-lockfile", which I do not know where it came from, but I got error initially which instructed to install this file. 
Thank you so much for your community effort.

**Comment by ChristianChiarulli** [comment]
Awesome! Closing
