### ISSUE TITLE
fzf config issue

### ISSUE THREAD

**Issue by mybigman** [ChristianChiarulli/nvim#24]
Hey Chris... Got a couple of issues with your config.

1. :Rg does not open a floating window, it opens up at the bottom.

2. The floating window has these ugly thick borders.

<img width="1303" alt="Screen Shot 2020-06-07 at 10 57 12 pm" src="https://user-images.githubusercontent.com/1289916/83970600-e6d1b100-a919-11ea-9453-b645251d5870.png">

**Comment by ChristianChiarulli** [comment]
hmm can you post a link to your config? Also if you want you can try joining the discord for some help from the community.

**Comment by mybigman** [comment]
I am using another config now which has resolved the error.
