### ISSUE TITLE
[vista.vim] Error when calling

### ISSUE THREAD

**Issue by TyNguyen2k1** [ChristianChiarulli/nvim#28]
Hi everybody! I encountered the following error.
![Annotation 2020-06-19 115455](https://user-images.githubusercontent.com/64082226/85103793-8d2e8800-b231-11ea-9b7a-a625cfa00cfc.jpg)
How can I fix it?
Here is ': checkheadlth':
Thank you for you help!

> 
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#rnvimr#check
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - ERROR: Ranger not Found

## Pynvim
  - OK: Version: 0.4.1

## Ueberzug (optional)
  - WARNING: Ueberzug is not found in Python Lib

## RPC
  - OK: Install lib for checkhealth successfully
  - ERROR: RPC: timeout 3s
  - ERROR: Vim(call):E900: Invalid channel id
  - OK: Clean lib for checkhealth successfully

health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - OK: nvr is OK

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          python not found in search path or not executable.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.2
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.19.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

**Comment by urwrstkn8mare** [comment]
same

**Comment by ChristianChiarulli** [comment]
I have to ask, did you install ranger?

**Comment by TyNguyen2001** [comment]
> nvm thought this was the ranger issue, I'll try to reproduce

Thanks

**Comment by Saurav-Paul** [comment]
Hey faced the same issue, How to solve? at least how can i disable this error text?

**Comment by smikeblog** [comment]
Try to comment in file  
                  **nvim/plug-config/vista.vim**
 the line 
                  **let g:vista_default_executive = 'coc'**
It seems to me that it is node error on tags

**Comment by ChristianChiarulli** [comment]
The error should be fixed for now. You may want to follow this issue [here](https://github.com/liuchengxu/vista.vim/issues/85) or consider opening an issue on the vista.vim repo.
