### ISSUE TITLE
Emmet?

### ISSUE THREAD

**Issue by apiening** [ChristianChiarulli/nvim#3]
Thank you for your nvim-config!

I followed your video on youtube and it looked to me that you had some sort of **emmet** plugin enabled.
But I can't find it in the config.

Did you drop it on purpose or was it replaced by something else?

**Comment by santigo-zero** [comment]
You can install the emmet language server with `:LspInstall emmet_ls` and it should start working out of the box.

**Comment by apiening** [comment]
Thank you, it worked!
I'm still struggling to understand the working / key bindings even for the essential **nvim** plugins, but it does get better.
