### ISSUE TITLE
FZF default command ERROR

### ISSUE THREAD

**Issue by 0xRainy** [ChristianChiarulli/nvim#32]
@ChristianChiarulli sorry to revive but I have ripgrep installed and getting the same error as #13

Changing let `$FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git/**'"`
to `let $FZF_DEFAULT_COMMAND="rg --files --hidden --glob=!.git/**"` fixes this issue for me

Running the command in my term works fine.
Running :Rg inside nvim also works fine

I don't think I need floatingterm plugin (I dont have it installed) but you tell me.

I'm on windows 10 using WindowsTerminal with powershell
also getting this after executing a FZF search with which-key>search>FZF, complete the search, upon next keypress the error shows up (above issue fixed, this must be a separate issue):

```Error running ^"C:\Users\rainy\.config\nvim\autoload\plugged\fzf/bin/fzf^" --history ^"C:\Users\rainy\.local\share\fzf-history/FZF^" ^"--color=bg+:242,border:0,spinner:11,hl:14,header:14,info:81,pointer:11,marker:11,prompt:11,hl+:11^" ^"--multi^" ^"--prompt^" ^"C:\r\chatterino2\\^" --expect=ctrl-v,ctrl-x,ctrl-t --no-height > C:\Users\rainy\AppData\Local\Temp\nvimOKyc7v\0```

**Comment by ChristianChiarulli** [comment]
Unfortunately I don't have plans to support windows. Please let me know if you find a fix.
