### ISSUE TITLE
I failed to install Nvim Mach 2 by the command line

### ISSUE THREAD

**Issue by alexya** [ChristianChiarulli/nvim#34]
I like your settings for neovim very much and have had a try.

MacBook Pro (15-inch, 2016)
version 10.15.5

node
v10.21.0

I installed the nvim with homebrew `brew install nvim`
nvim --version 
neovim: stable 0.4.2 (bottled)

then I ran the command under current user account.
`bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/nvim/master/utils/install.sh)`
everything was good and without any errors in the command line(terminal)

But when I opened the neovim by `nvim`, I got errors like this:
![image](https://user-images.githubusercontent.com/2831220/85944920-d1760280-b96c-11ea-8066-5d9b91af9786.png)

and after I pressed any key, I got many coc errors like:
![image](https://user-images.githubusercontent.com/2831220/85944951-f10d2b00-b96c-11ea-8fcc-8e7cf04fa199.png)

I also tried to reinstall the match 2 with sudo but still failed with errors "bad file descriptor"
![image](https://user-images.githubusercontent.com/2831220/85944974-1ef26f80-b96d-11ea-97f1-a0b3e9173975.png)

Furthermore, it seems most of the settings of nvim failed to work such as the theme, colors, etc. 
I want to make my nvim look like the theme in your video such as "https://www.youtube.com/watch?v=65Wq4fjREUU". 
e.g. 
![image](https://user-images.githubusercontent.com/2831220/85945030-827c9d00-b96d-11ea-84ff-0aa040b1b90b.png)

Could u please give me some help? thx.

**Comment by ChristianChiarulli** [comment]
The first thing I would recommend is installing at least neovim 4.3. If you still have issues let me know.

**Comment by alexya** [comment]
@ChristianChiarulli 
Updated: 
I updated my neovim to 0.4.3 
![Screen Shot 2020-06-29 at 12 06 44 PM](https://user-images.githubusercontent.com/2831220/85971926-0f246b00-ba01-11ea-90a3-3c4a7a96b553.png)

And I tried again to ran the install.sh. the errors like: 
![Screen Shot 2020-06-29 at 12 04 31 PM](https://user-images.githubusercontent.com/2831220/85971947-22373b00-ba01-11ea-8e71-40a7478f35e4.png)
![Screen Shot 2020-06-29 at 12 04 55 PM](https://user-images.githubusercontent.com/2831220/85971957-2d8a6680-ba01-11ea-8c9f-0a94e5beca28.png)

More information: 
the step `Installing plugins...` took a lot of time, and I was required to input the password. 

The result is the same as previous: 
![Screen Shot 2020-06-29 at 12 10 32 PM](https://user-images.githubusercontent.com/2831220/85972137-a5f12780-ba01-11ea-9a25-694f072f5102.png)
![Screen Shot 2020-06-29 at 12 10 43 PM](https://user-images.githubusercontent.com/2831220/85972140-a8ec1800-ba01-11ea-92e3-4a00d3f1c964.png)

From the details, the download process succeeded, but the rename failed.

**Comment by kevyyar** [comment]
> @ChristianChiarulli
> Updated:
> I updated my neovim to 0.4.3
> ![Screen Shot 2020-06-29 at 12 06 44 PM](https://user-images.githubusercontent.com/2831220/85971926-0f246b00-ba01-11ea-90a3-3c4a7a96b553.png)
> 
> And I tried again to ran the install.sh. the errors like:
> ![Screen Shot 2020-06-29 at 12 04 31 PM](https://user-images.githubusercontent.com/2831220/85971947-22373b00-ba01-11ea-8e71-40a7478f35e4.png)
> ![Screen Shot 2020-06-29 at 12 04 55 PM](https://user-images.githubusercontent.com/2831220/85971957-2d8a6680-ba01-11ea-8c9f-0a94e5beca28.png)
> 
> More information:
> the step `Installing plugins...` took a lot of time, and I was required to input the password.
> 
> The result is the same as previous:
> ![Screen Shot 2020-06-29 at 12 10 32 PM](https://user-images.githubusercontent.com/2831220/85972137-a5f12780-ba01-11ea-9a25-694f072f5102.png)
> ![Screen Shot 2020-06-29 at 12 10 43 PM](https://user-images.githubusercontent.com/2831220/85972140-a8ec1800-ba01-11ea-92e3-4a00d3f1c964.png)
> 
> From the details, the download process succeeded, but the rename failed.

Did you resolve this? I get the same errors here on my Mac

**Comment by alexya** [comment]
@kevyyar No. I have not resolved the issue.

**Comment by arrase21** [comment]
@alexya delete coc directory, (work for me)

**Comment by Snoussi88** [comment]
> @alexya delete coc directory, (work for me)
thank you so much it worked for me finally

**Comment by satyrnhub** [comment]
@alexya Try arrase21's solution. If it works, you should close this. I might make a pull request that autodeletes the coc directory when installing if possible.

**Comment by ChristianChiarulli** [comment]
I may just move the ~/.config/coc directory to ~/.config/coc.old

**Comment by satyrnhub** [comment]
yeah, that makes sense to me

**Comment by satyrnhub** [comment]
Recent commits seem to fix this.

**Comment by ChristianChiarulli** [comment]
> Recent commits seem to fix this.

You're right I think we can close this.
