### ISSUE TITLE
Error when calling CocActionAsync('documentSymbols'): 'Cannot read property ''getDocumentSymbols'' of undefined' 

### ISSUE THREAD

**Issue by PaoloTorregroza** [ChristianChiarulli/nvim#36]
I get this error when I start neovim, I fully remove my last neovim config, and install this whit the all in one command.

![Screenshot from 2020-07-08 22-08-56](https://user-images.githubusercontent.com/29853181/86992844-0c93e500-c168-11ea-8796-d3fbf1004c44.png)

I already try CocUpdate but I still having the error

**Comment by visualexploreradds** [comment]
I get the same error. I have tried to find out online a way to solve this, but as of yet to absolutely no avail. I too would appreciate any help. Kindest regards, Adam

**Comment by ChristianChiarulli** [comment]
It's an issue with vista not CoC, I'll look into it I've seen other people with this error but I haven't been able to reproduce it.

**Comment by visualexploreradds** [comment]
Thanks for replying Christian. And thanks for your fine neovim scripts and videos. They have made my life ever so easier. And your videos have taught me a lot. Regards, Adam

**Comment by ChristianChiarulli** [comment]
I just started getting the error after updating. I recommend putting an issue in here: [Vista issues](https://github.com/liuchengxu/vista.vim/issues)

I'm glad you're finding the videos helpful, I recommend joining the discord if you haven't there's a lot of helpful people there as well.

**Comment by PaoloTorregroza** [comment]
This issue must be here  [Vista issues](https://github.com/liuchengxu/vista.vim/issues) (Thank you Christian)
