### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by collegeimprovements** [ChristianChiarulli/nvim#4]
Hi @ChristianChiarulli ,
I cloned the repo and themes are applied. 
However I'm not able to use leader key ? 
Can it be a mac-specific thing ? Do I need to do something differently for mac?

**Comment by ChristianChiarulli** [comment]
I haven't implemented which key yet in the series. I will in the next two videos. The functionality I think you're looking for is which key. 

The leader key should work fine if you want to make some custom mappings until then. If you want the functionality now I suggest checking out the stable branch which has the config I used in my first video. 

Thanks for opening an issue!

**Comment by collegeimprovements** [comment]
Hi @ChristianChiarulli,
Yes....`which-key` is what i really need to setup. I'll wait for the video ☺️
All other functionality worked but `leader` key was not working.
After I set `set timeoutlen=1000`, `leader` key seems to be working.

Thanks a lot for the video-series. I'm learning a lot from it.

Few more requests:
1. Please include some kind of `snippet` tool or manager if possible.
2. Please make a video on navigating between files/folders. Shortcuts, `ctrl-0` and friends if possible. e.g. How do you access recently used file that's not in the current folder.

**Comment by ChristianChiarulli** [comment]
Which key is now built in.

Snippets should be coming soon. I'll be using CoC snippets I think. 

Also eventually I would like to make a tutorial on basic vim commands, I think I'll do that over the comming weeks.

**Comment by collegeimprovements** [comment]
Thanks a lot @ChristianChiarulli. I'm closing this issue now 😊
