### ISSUE TITLE
jj for escape not working

### ISSUE THREAD

**Issue by angkosal** [ChristianChiarulli/nvim#40]

**Comment by ChristianChiarulli** [comment]
I think I have jk set

**Comment by angkosal** [comment]
@ChristianChiarulli, i have add jj one more, sir

**Comment by ChristianChiarulli** [comment]
I just tested and it works, you should try increasing you keypress speed or decrease the delay between keypresses

**Comment by angkosal** [comment]
Nice, Thanks you very much for help brother
