### ISSUE TITLE
Failed to install nvim setup

### ISSUE THREAD

**Issue by pablooaliaga** [ChristianChiarulli/nvim#43]
Hi, I'd like to install your vim setup, but I think there's a missing file in the master branch because I keep getting this error. 

bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/nvim/master/utils/install.sh)
Installing Nvim Mach 2
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
Cloning Nvim Mach 2 configuration
Cloning into '/home/pablo/.config/nvim'...
remote: Enumerating objects: 153, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 1348 (delta 55), reused 121 (delta 31), pack-reused 1195
Receiving objects: 100% (1348/1348), 5.50 MiB | 5.55 MiB/s, done.
Resolving deltas: 100% (726/726), done.
**mv: cannot stat '/home/pablo/.config/nvim/utils/init.vim': No such file or directory**

**Comment by ChristianChiarulli** [comment]
I know how that happened, I'll push a fix for it now

**Comment by ChristianChiarulli** [comment]
Ok should be fixed my bad

**Comment by pablooaliaga** [comment]
Thanks!, but now there is the following problem:

Installing Nvim Mach 2
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
**/proc/self/fd/13: line 154: moveoldcoc: command not found**

I think you misstyped the method name moveold**n**coc in the bash file install.sh

**Comment by ChristianChiarulli** [comment]
Ok now it's fixed for real this time, that's what I get for trying to sneak a feature in.

**Comment by pablooaliaga** [comment]
Thanks a lot. Now it worked
