### ISSUE TITLE
Better which-key session management

### ISSUE THREAD

**Issue by unknowledgeable** [ChristianChiarulli/nvim#45]
Hi @ChristianChiarulli I've been following your tutorials on YouTube and setting my init.vim manually instead of pulling your whole config and added a little something I think you may like so thought I'd share:

```
let g:which_key_map.S = {
      \ 'name' : '+Session' ,
      \ 'c' : [':SClose'          , 'Close Session']  ,
      \ 'd' : [':SDelete'         , 'Delete Session'] ,
      \ 'l' : [':SLoad'           , 'Load Session']     ,
      \ 's' : [':Startify'        , 'Start Page']     ,
      \ 'S' : [':SSave'           , 'Save Session']   ,
      \ }

```

This makes navigating saved sessions a bit more natural for me and the only difference is that you have to type an extra S to save the session.

Thanks for the great work and all the videos, really looking forward to more!

**Comment by ChristianChiarulli** [comment]
implemented

**Comment by unknowledgeable** [comment]
Just noticed that the `:SDelete` in this config doesn't work as expected, not sure how to fix though
