### ISSUE TITLE
coc-explorer causes nvim to close on buffer delete

### ISSUE THREAD

**Issue by ainharan** [ChristianChiarulli/nvim#46]
Hi I am having an issue with buffers deletion when using coc-explorer.

I observed the following:
- when I open multiple files in different buffers using coc-explorer and try delete a single buffer with the `:bd` command, nvim quits.
- when I open multiple files in different buffers using coc-explorer and then quit coc-explorer with `:q` and then close a single buffer nvim deletes the buffer as normal 
- further when I use other methods of opening files such as fzr or ranger and no coc-explorer at all I am not getting this issue.

**Comment by ChristianChiarulli** [comment]
hmm I think I've noticed a similar issue. If you think it's coc-explorer, I recommend putting an issue in here:

https://github.com/weirongxu/coc-explorer

**Comment by ainharan** [comment]
Yea I was trying to create a function that closes coc-explorer and then deletes the buffer and then re-opens coc-explorer on `:bd`, but I couldnt get it working.

**Comment by ChristianChiarulli** [comment]
Ok so I just added a new plugin called bbye

Try calling `:Bdelete` in place of `bd` now

Here's a link: https://github.com/moll/vim-bbye

**Comment by ainharan** [comment]
Thanks it works!

Also side note would you happen to know how I can get coc-explorer to open after startify intial screen?
I was able to starts coc-explorer along with Startify, by adding `autocmd VimEnter * :CocCommand explorer` to  in `plug-config/coc-vim`.
But I wasn't able to figure out how to start after startify. Here is my failed attempt at an autocmd which errors:
`autocmd BufEnter * if ( &filetype != 'startify') | :CocCommand explorer | wincmd w | endif`

**Comment by ChristianChiarulli** [comment]
I'm not sure how that would work, there may be something you could add in coc-settings maybe...

Closing due to original issue being solved.
