### ISSUE TITLE
error in function 'nvim_open_win'

### ISSUE THREAD

**Issue by abissaldev** [ChristianChiarulli/nvim#47]
![Jul29-10-29](https://user-images.githubusercontent.com/97896243/181770847-1341e8b2-070f-42ce-af12-ec63388c6dbf.png)

the error only appears after moving the line

**Comment by Livingnight** [comment]
I'm experiencing this same issue. It doesn't happen with anything related to telescope I've found but neotree/nvim-tree/lir/jabs/toggleterm/your custom buffer switcher all run into this error at some point. I'm unsure if this is related to the extensions or the underlying neovim api and the way they create 
![image](https://user-images.githubusercontent.com/26702985/181834161-57961122-51e6-499f-a9ad-7d63733c31bb.png)
-
![image](https://user-images.githubusercontent.com/26702985/181834313-18504199-27f1-4d61-884a-a36da2dc4bc4.png)

![image](https://user-images.githubusercontent.com/26702985/181834604-189f53e9-35e2-49f2-b25f-0b3ac608c2d1.png)

**Comment by krshrimali** [comment]
Yep, have observed this as well. Raised a related issue here: #46

**Comment by Mr-istov** [comment]
I'm experiencing the same issue using:

```
NVIM v0.8.0-dev-701-g2a9c9371b
Build type: Release
```

I think it might be related to neovim, there is an open issue related to the same problem: https://github.com/neovim/neovim/issues/19458

**Comment by Mr-istov** [comment]
I found a similar issue to this, here: https://github.com/sindrets/diffview.nvim/issues/185
And after disabling the `user.autocommands` from the `init.lua`, the problem is fixed. I tried to debug a little more, to see which code is causing the issue, and after commenting out parts of the code, this is the code that causes the issue to appear:
```lua
if vim.fn.has "nvim-0.8" == 1 then
  vim.api.nvim_create_autocmd(
    { "CursorMoved", "CursorHold", "BufWinEnter", "BufFilePost", "InsertEnter", "BufWritePost", "TabClosed" },
    {
      callback = function()
        require("user.winbar").get_winbar()
      end,
    }
  )
end
```
