### ISSUE TITLE
Question: which plugin/option is responsible for automatic symbols highlighting?

### ISSUE THREAD

**Issue by av-maslov** [ChristianChiarulli/nvim#48]
Hello.

Which plugin/option is responsible for automatic symbols highlighting under cursor?

**Comment by erlonbie** [comment]
ls_highlight_document(client)  inside handler.lua

> Hello.
> 
> Which plugin/option is responsible for automatic symbols highlighting under cursor?

ls_highlight_document(client)  inside handler.lua

**Comment by ChristianChiarulli** [comment]
I'm using vim-illuminate

**Comment by av-maslov** [comment]
Thanks a lot!
