### ISSUE TITLE
Unicode conversion 

### ISSUE THREAD

**Issue by broans** [ChristianChiarulli/nvim#5]
Nice repo, good work! I do not know if it is when the code is uploaded or downloaded from github when there is an error in the conversion occur. In for example handlers.lua:
`{ name = "DiagnosticSignError", text = " " }`

I suggest using the hex-value instead to make the code more platform independent:
`{ name = "DiagnosticSignError", text = "\u{274C}" }`

**Comment by ChristianChiarulli** [comment]
I should do this, but I'm far to lazy to replace them all now.
