### ISSUE TITLE
Can't read viminfo file

### ISSUE THREAD

**Issue by jtfogarty** [ChristianChiarulli/nvim#5]
I just pulled from your repo and am getting the below error;

<img width="464" alt="Screen Shot 2020-05-07 at 8 03 30 PM" src="https://user-images.githubusercontent.com/6708730/81359263-454b0b80-909e-11ea-98bb-2386e8213541.png">

**Comment by ChristianChiarulli** [comment]
https://github.com/mhinz/vim-startify/issues/306

It may be a permissions file. Let me know if this link helps if not I'll troubleshoot further.

**Comment by jtfogarty** [comment]
I might be mistaken but if I put the below in the init.vim file, I do not get this error;

```set viminfo='100,n$HOME/.config/nvim/autoload/plugged/vim-startify/test/viminfo'```

**Comment by ChristianChiarulli** [comment]
hmm, after I test this on a few more systems if I'm ever able to replicate this I'll try adding that.

**Comment by ChristianChiarulli** [comment]
seems to be fixed
