### ISSUE TITLE
EACCES: permission denied, rename '/tmp/nvimQ7ueu1/coc-snippets-SMqLIz' -> '/home/john/.config/coc/extensions/node_modules/coc-snippets' 

### ISSUE THREAD

**Issue by BioWare** [ChristianChiarulli/nvim#50]
Hello i **Installed in one command** your settings, and had this problems.
Every plugin gives same error that i should to rename plugs. After renaming and deleting **tmp/nvimQ7ueu1** folder, i restarted nvim. Folder was created again and errors steel there. Im new in all this stuff, hope you can tell me what does nvim wants from me. Thanks. Sorry for writing my problem in Issues section.
[screenshot](https://imgur.com/I50cKcd)

**Comment by aptigges21** [comment]
I was having the same problem until I realized I had to grant write privileges to the node_modules folder. Cd your way to `~/.config/coc/extensions` and something like this should do the trick:

`sudo chmod -R og=rwx node_modules`

Then I ran nvim and everything installed normally. 

Hopefully this helps

**Comment by BioWare** [comment]
Thanks a lot, it's really helped me! appreciate

**Comment by ChristianChiarulli** [comment]
seems solved
