### ISSUE TITLE
for windows ?

### ISSUE THREAD

**Issue by ChanManChan** [ChristianChiarulli/nvim#51]
what to change to make it work on windows 10 ?

**Comment by ChristianChiarulli** [comment]
To be honest I'm not sure I don't use Windows at all.

**Comment by ChanManChan** [comment]
sad :(

**Comment by haininhhoang94** [comment]
You can consider using Windows Subsystem for Linux. I will commit some changes so that they can provide gui support (via Alacritty, Windows Terminal, or fVim) as well 👍 

Thanks @ChristianChiarulli for inspire us!

**Comment by irishgreencitrus** [comment]
I know this is a bit late, but i've just changed some things around and got it to work natively on windows [here](https://github.com/irishgreencitrus/SolarVim#install-in-one-command). Let me know if you have any issues with this config setup.
