### ISSUE TITLE
Icons not working in explorer

### ISSUE THREAD

**Issue by ZeroTex** [ChristianChiarulli/nvim#55]
I'm having my icons come up like this after being fully setup. Everything else seems to work fine. (Side note: if anyone can figure out how to get WordPress PHP stubs working with a language server, that'd be great too!)

![Screenshot from 2020-09-13 09-26-31](https://user-images.githubusercontent.com/57423623/93020612-a4b4ad00-f5a3-11ea-8740-6b67abbb94b2.png)

**Comment by ChristianChiarulli** [comment]
Check out my video on nerdfonts
