### ISSUE TITLE
vim-which key config not working correctly

### ISSUE THREAD

**Issue by realkelvinperez** [ChristianChiarulli/nvim#56]
![Screen Shot 2020-09-13 at 9 22 49 PM](https://user-images.githubusercontent.com/9101885/93034198-47eade00-f607-11ea-8caf-c7e75b44ea19.png)

I copied all all of the setting from you vim-which key config and i'm getting a weird behavior where certain settings are not registering correctly.

**Comment by ChristianChiarulli** [comment]
You have leader commands in your config (probably in coc.vim) or a plugin is automatically sourcing leader commands. You can usually disable them. Checkout my gitgutter settings or check to see if you have leader commands defined outside of your which key dictionary.

**Comment by realkelvinperez** [comment]
Yup, you were correct i used the Rg command to look for <leader> and it looks like i had <leader>t being mapped inside FZF. Thank you for pointing me in the right direction.

Dude thank you so much for your work i've tried to figure out how to set up vim like an IDE for a while and i would constantly go back and forth but now i truly feel like this is an amazing workstation. I use tmux as well and its the best of both worlds 😄 

Keep it up dude.
