### ISSUE TITLE
Pyright doesn't start with your config

### ISSUE THREAD

**Issue by zstreet87** [ChristianChiarulli/nvim#57]
In `nvim/lua/user/lsp/settings/pyright.lua` the `cmd = { "py" }` line complains as `py` is not an executable. 

I have pyright installed and adding `cmd = { "pyright" }` doesn't start pyright once in a python file.  Commenting out this line completely, allows pyright to attach to a python buffer.

Seems like a simple thing but I'm not sure what is the issue.  Do you have `pyright` aliased to `py` on your system?  Still would have thought adding `pyright` as the `cmd` would fix it but no dice :/

**Comment by CharlesChiuGit** [comment]
I remove that line too.

**Comment by Alfredo-Vargas** [comment]
Same problem here, I commented that line

**Comment by marc-brouard** [comment]
Also had this issue, would be nice to know how Christian has his setup, purely from curiosity

**Comment by acuriel** [comment]
probably `py` is an alias for `python` or `python3`
