### ISSUE TITLE
Looking for Sample Configs

### ISSUE THREAD

**Issue by gpaulsen** [ChristianChiarulli/nvim#59]
Hello.

  Your blog https://www.chrisatmachine.com/blog/category/neovim/22-vscodium-neovim links to some missing files reportedly in this repo.  Unfortunately I can't seem to find them, and in looking through the history, it appears they may never have existed in this repo?  I also don't see another repo that they may be in.
  
   Any help finding these sample vscode configs listed on your blog site?
   
   Thanks!

**Comment by gpaulsen** [comment]
I do see that the blog entry is from 2020, and the first commit in this repo is 2021. :(

**Comment by ChristianChiarulli** [comment]
checkout the pinned comment on that YT video

**Comment by gpaulsen** [comment]
Ah, thanks!  I see in your video: https://www.youtube.com/watch?v=g4dXZ0RQWdw, there is a pinned comment that I missed that points to: https://github.com/LunarVim/LunarVim/blob/4625145d0278d4a039e55c433af9916d93e7846a/vscode/settings.vim
