### ISSUE TITLE
On Fresh install with curl script on Mac colors seem very off

### ISSUE THREAD

**Issue by david-saint** [ChristianChiarulli/nvim#65]
I used the curl script to install nvcode but after installation, the colors seem very off

<img width="1302" alt="Screenshot 2020-09-27 at 18 49 49" src="https://user-images.githubusercontent.com/11745653/94372022-7336f800-00f2-11eb-8cdc-183083579355.png">

I use Oh-My-Zsh

**Comment by ChristianChiarulli** [comment]
huh, I've never seen this before. I'll have to see if anyone else runs into this.

**Comment by geo7** [comment]
🖐️ here too 

![image](https://user-images.githubusercontent.com/8526351/95529833-f6e6c380-09d3-11eb-9499-0da6a6e5ab43.png)


other themes seem to be pretty messy as well for some reason - if there's anything concrete to try let me know and hopefully I'll look when possible.

**Comment by ChristianChiarulli** [comment]
Can anyone confirm if this is still an issue with the latest config?

**Comment by CalamariDude** [comment]
I just downloaded it, seems to still be the case, I haven't done the suggestions above though.

**Comment by ChristianChiarulli** [comment]
What version of neovim are you on?

**Comment by CalamariDude** [comment]
![Uploading Screen Shot 2020-11-14 at 2.05.17 AM.png…]()

**Comment by david-saint** [comment]
Could it be because of a previous oh-my-zsh theme setting?

**Comment by SaschaHeyer** [comment]
same issue here =)

**Comment by jordisantamaria** [comment]
It's still happening, I move from mac default terminal to iterm2 because that, anyway worth It.

**Comment by ChristianChiarulli** [comment]
for now I guess the solution is to move to iTerm2.

**Comment by machow** [comment]
Ah--as a new lunarvim user, it took a couple hours to google my way to this issue (definitely did not think it was terminal related..!). I wonder if there's a good place to add a note? What do you think of a "Tips for Mac Users" section on [this page](https://www.lunarvim.org/01-installing.html#tips-for-wsl-2-users)?
