### ISSUE TITLE
jdtls debugger

### ISSUE THREAD

**Issue by Ichikasai** [ChristianChiarulli/nvim#66]
I found an issue with jdtls debugger while trying to set it up myself and wanted to share just in case it is a bug that also affected other people. So currently in the lsp/handler file, the code for jdtls currently is like this: 
if client.name == "jdt.ls" then
    vim.lsp.codelens.refresh()
    if JAVA_DAP_ACTIVE then
      require("jdtls").setup_dap { hotcodereplace = "auto" }
      require("jdtls.dap").setup_dap_main_class_configs()
    end

The problem with it (at least for me) was that insteat of jdtls, the code has it written:
if client.name == "jdt.ls" then

After changing jdt.ls to jdtls, the debugger started working as expected. So, hopefully this helps and if not, just wanted to share in case anyone else was having a similar issue.

**Comment by erlonbie** [comment]
Thank you so much @Ichikasai , after a massive plugins update, I was having this issue and having no idea what was wrong.
