### ISSUE TITLE
quickscope colors

### ISSUE THREAD

**Issue by mybigman** [ChristianChiarulli/nvim#7]
I am currently using [your config](https://github.com/ChristianChiarulli/nvim/blob/master/plug-config/quickscope.vim)  ATM.

Using [night owl theme](https://github.com/haishanh/night-owl.vim) and making changes to quickscope colors in the config has no effect.

If I disable the theme it then works as per normal.

Any ideas?

_BTW loving your videos and its making me use nvim more and more thanks to you._

**Comment by ChristianChiarulli** [comment]
@mybigman hmm I'll have to install the theme and check it out. 

I actually used to use nightowl, but not when I had quickscope installed. 

I'll try and look into it soon. 

Also I'm glad your enjoying the content!

**Comment by lalitmee** [comment]
@mybigman , try putting the `plug-config/quickscope.vim` at the end of the `init.vim`. I think it may be the sequence of sourcing the files in `init.vim`. I was also facing the same issue with `quickscope` colors. I simply changed the order.

**Comment by ChristianChiarulli** [comment]
recommend porting nightowl to my nvcode colorscheme repo, I will probably do this eventually, but I won't support any other colorschemes explicitly.
