### ISSUE TITLE
.config/nvim/lua/user/nvim-tree.lua:26: attempt to index field 'notify' (a nil value)

### ISSUE THREAD

**Issue by apiening** [ChristianChiarulli/nvim#71]
Just tried this config with `NVIM v0.8.0` on `Mac OS X`, but it fails with an error on startup:
```
Error detected while processing /Users/myuser/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/myuser/.config/nvim/lua/user/nvim-tree.lua:26: attempt to index field 'notify' (a nil value)
stack traceback:
        /Users/myuser/.config/nvim/lua/user/nvim-tree.lua:26: in main chunk
        [C]: in function 'require'
        /Users/myuser/.config/nvim/init.lua:15: in main chunk
```
Any idea what this is caused by?

**Comment by push-on** [comment]
in ur nvim-tree.lua
try commenting out this part of ur code
`
---@diagnostic disable-next-line: unused-local
local function notify_level(level)
  return function(msg)
    vim.schedule(function()
      vim.api.nvim_echo({ { msg, "WarningMsg" } }, false, {})
    end)
  end
end

utils.notify.warn = notify_level(vim.log.levels.WARN)
utils.notify.error = notify_level(vim.log.levels.ERROR)
utils.notify.info = notify_level(vim.log.levels.INFO)
utils.notify.debug = notify_level(vim.log.levels.DEBUG)
`

**Comment by apiening** [comment]
Thank you very much @push-on!

After commenting out these lines, `nvim` launches and is working fine for me.
