### ISSUE TITLE
which key bindings not set

### ISSUE THREAD

**Issue by shivahnshankar** [ChristianChiarulli/nvim#71]
I have cloned the latest version of NVcode and configured the paths to nvim and init.vim in VS Code. However, the which key bindings are the default, and i am at a loss to troubleshoot why. Any pointers?

**Comment by rmGFW** [comment]
> I have cloned the latest version of NVcode and configured the paths to nvim and init.vim in VS Code. However, the which key bindings are the default, and i am at a loss to troubleshoot why. Any pointers?

I also have problem on vscode  
when I down leader key ,
the error popped up

2020-10-21T13:49:58.498Z whichkey.show failed, args: [] error: command 'whichkey.show' not found

**Comment by ahmed-rezk-dev** [comment]
Me too. the same error.

**Comment by ahmed-rezk-dev** [comment]
Hey.

I Just fixed it.

First of all VSCodium not working well with me. there is a lot of extensions are not exist when I search. which include.
[https://marketplace.visualstudio.com/items?itemName=VSpaceCode.whichkey](url)

It's the one you have to install on VScode to fix the problem. again it only appears on VScode.

Useful article: [https://www.chrisatmachine.com/Neovim/22-vscodium-neovim/]()

Hope that's will help you guys.

Thank you!

**Comment by ChristianChiarulli** [comment]
the vscode bindings are in my nvim repo. You will have to move the keybindings.json and settings.json there yourself. https://github.com/ChristianChiarulli/nvim/tree/master/utils/vscode_config
