### ISSUE TITLE
Treesitter, galaxyline and other issues since upgrading

### ISSUE THREAD

**Issue by alechp** [ChristianChiarulli/nvim#76]
## Problem

<details><summary>What I see when opening nvim</summary>
<img src="https://user-images.githubusercontent.com/3058939/98020155-7c814780-1db7-11eb-9afd-e90d50eee0e0.png" />
<code>
Error detected while processing function plug#end:
line   86:
E484: Can't open file /share/nvim/syntax/syntax.vim
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/general/settings.vi
m:
line    4:
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/themes/nvcode.vim:
line    4:
E484: Can't open file /share/nvim/syntax/syntax.vim
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/init.vim:
line   36:
E5113: Error while calling lua chunk: vim.lua:269: module 'vim.uri' not found:
        no field package.preload['vim.uri']
        no file './vim/uri.lua'
        no file '/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/uri.lua'
        no file '/usr/local/share/lua/5.1/vim/uri.lua'
        no file '/usr/local/share/lua/5.1/vim/uri/init.lua'
        no file '/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/lua/5.1/vim/uri.lua'
        no file '/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/lua/5.1/vim/uri/init.lua'
        no file './vim/uri.so'
        no file '/usr/local/lib/lua/5.1/vim/uri.so'
        no file '/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/lib/lua/5.1/vim/uri.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/autoload/plugged/nv
im-treesitter/plugin/nvim-treesitter.vim:
line   12:
E5108: Error executing lua ...autoload/plugged/nvim-treesitter/lua/nvim-treesitter.lua:3: nvim-treesitter requires a more rec
ent Neovim nightly version!
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/autoload/plugged/pl
ayground/plugin/nvim-treesitter-playground.vim:
line    3:
E5108: Error executing lua ...ad/plugged/playground/lua/nvim-treesitter-playground.lua:8: loop or previous error loading modu
le 'nvim-treesitter'
opening: 0 / 1
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/autoload/plugged/vi
m-polyglot/plugin/polyglot.vim:
line    8:
E484: Can't open file /share/nvim/syntax/syntax.vim
Error detected while processing BufReadPost Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'galaxyline'
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'galaxyline'
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'galaxyline'
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'galaxyline'
</code>
</details>

<details><summary>When I see after running :PlugUpdate</summary>
<img src="https://user-images.githubusercontent.com/3058939/98020190-873bdc80-1db7-11eb-8ecd-8b912d6de987.png" />
<code>
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/autoload/plugged/vim-polyglot/plugin/polyglot.vim:
line    8:
E484: Can't open file /share/nvim/syntax/syntax.vim
</code>
</details> 

## Cause
Been about two weeks since I ran into this issue. Still investigating, just wanted to post this early since it seems like others are running into issues as well

## Environment
- neovim `0.5` (just manually downloaded since 0.4.4 was failing and treesitter suggests 0.5)
- mac `10.15.16`

**Comment by ChristianChiarulli** [comment]
Does this help anything:

```brew install --HEAD neovim # Latest

brew upgrade neovim --fetch-HEAD # Sometimes you need to update```

**Comment by alechp** [comment]
❌ `fails`
> `brew install neovim --HEAD`

✅ `succeeds`
> `brew install neovim && brew upgrade neovim --fetch-HEAD`

---

Also updated xcode to 12.1 (was 12.0 previously). Doesn't solve the issue unfortunately.

**Comment by alechp** [comment]
Figured it out. 

Combination of:
- Updating xcode from 12.0 to 12.1
- Using neovim 0.5 (ie. installing manually from Github instead of using homebrew)
- Uninstalling pyenv, removing PATH vars and installing miniconda

**Comment by ChristianChiarulli** [comment]
That's interesting, nice work.

**Comment by alechp** [comment]
Had to repeat this on my MBP and forgot one step. 
Adding here in case it gives someone else difficulty:

## If you see this in your healthcheck...
> After seeing a wall of lua errors re: treesitter, lua, galaxyline, etc.

<img width="1552" alt="Screen Shot 2020-11-09 at 9 46 34 AM" src="https://user-images.githubusercontent.com/3058939/98581240-0593f500-2276-11eb-9c49-b34d5e68cfc1.png">

## Remember to upgrade pynvim

<img width="1552" alt="Screen Shot 2020-11-09 at 10 17 05 AM" src="https://user-images.githubusercontent.com/3058939/98581352-36742a00-2276-11eb-9904-776bc323aeb8.png">

<img width="832" alt="Screen Shot 2020-11-09 at 10 20 17 AM" src="https://user-images.githubusercontent.com/3058939/98581367-3d02a180-2276-11eb-80f4-35d48ee09dfd.png">

**Comment by juniovitorino** [comment]
A clean install in Mojave not works for me at all, unfortunately.  All error above happen even the difference is XCode Version 11.3.1.

**Comment by ChristianChiarulli** [comment]
You need the newest version of neovim 0.5.
