### ISSUE TITLE
Python provider issues since vimspector update

### ISSUE THREAD

**Issue by alechp** [ChristianChiarulli/nvim#77]
## Context

Just updated. Now several things are throwing. It seems to be sporadic (eg. sometimes it happens when I'm toggling coc-explorer). 

## Possible root problem

My assumption is that all of this boils down to a problem with the python3 provider. What I'm trying to figure out is why miniconda is no longer working with NVCode

## Symptoms
One issue that I've been able to consistently reproduce is find+replace

Steps:
1. Open vim to any file 
2. Trigger find+replace `leader + a`
3. Specify "file" `f`

<details><summary><b>Healthcheck provider<b /></summary>

<img src="https://user-images.githubusercontent.com/3058939/98417822-7fd63680-2036-11eb-97ff-7d7d56f01355.png" />
<code>
Error detected while processing /Users/alechp/Code/alechp/.repositories/config-backup/Mackup/.config/nvim/autoload/plugged/vi
mspector/autoload/vimspector.vim:
line  319:
E319: No "python3" provider found. Run ":checkhealth provider"
Error detected while processing function which_key#start[49]..which_key#window#show[12]..which_key#wait_for_input[17]..<SNR>2
5_handle_input[4]..<SNR>25_show_next_level_mappings[4]..which_key#window#show[12]..which_key#wait_for_input[17]..<SNR>25_hand
le_input:
line   10:
E171: Missing :endif
Error detected while processing function which_key#start[49]..which_key#window#show[12]..which_key#wait_for_input[17]..<SNR>2
5_handle_input:
line    4:
E171: Missing :endif</code>

</details>

<details><summary><b>Some of the errors I've seen since update</b></summary>
1. Missing tab from coc-explorer <br />
<img alt="missing tab" src="https://user-images.githubusercontent.com/3058939/98418048-f410da00-2036-11eb-9211-571368e5464b.png" />

2. Trying to quit after updating plugins

<img src="https://user-images.githubusercontent.com/3058939/98418154-2de1e080-2037-11eb-8e92-409b20b09176.png" />

3. Trying to move between tabs
<img src="https://user-images.githubusercontent.com/3058939/98418306-6d103180-2037-11eb-8df8-5a7a0234f087.png" />

4. Another coc related error
<img src="https://user-images.githubusercontent.com/3058939/98418464-d2fcb900-2037-11eb-8265-5277e8f3550d.png" />

</details>

**Comment by ChristianChiarulli** [comment]
What's your neovim version?

**Comment by alechp** [comment]
0.5. Been about a week since I last updated. 

### What I've been able to determine so far
**1. The coc explorer issue seems to occur when** 
a) when I `leader + e` too quickly after opening vim (assume it's a dependency race case since my system isn't struggling for memory)
b) sporadically after using Far

**2. Far doesn't seem to work at all anymore**
> I will open a new issue after I've investigated further. But here's a quick summary of what I'm seeing:
a) In file mode, nothing shows
b) In project mode, preview window returns results, but replacing included items "works" in the preview window. This fails if I manually type `:Fardo` or use the `s` keymapping.  

I will create a separate issue for Far at some point once I dig more. Closing this for now.
