### ISSUE TITLE
gist

### ISSUE THREAD

**Issue by klooj** [ChristianChiarulli/nvim#78]
https://github.com/ChristianChiarulli/nvim/blob/86366002e29ccac58bf99ac24ae16cbf77d2c093/utils/vscode_config/settings.json#L971

I'm still pretty new to this game, but this line seems like a problem to me.

Your blog has been a tremendous help and I use your repo as a template. Talisman caught that line when I tried pushing to my private config.

**Comment by ChristianChiarulli** [comment]
hmmm not sure if that gist give you write access. You should be able to just swap it out for whatever gist id you create.

**Comment by kludgeon** [comment]
gotcha. i get it now. i thought it was a potential security issue.

**Comment by ChristianChiarulli** [comment]
thanks for looking out, I should probably remove it anyway, I'll leave this up until I do.
