### ISSUE TITLE
garbage in the screen

### ISSUE THREAD

**Issue by Blackbear78** [ChristianChiarulli/nvim#79]
![Captura de Pantalla 2020-11-13 a la(s) 12 56 34](https://user-images.githubusercontent.com/74268641/99110408-f7b0dd80-25af-11eb-8f6b-827aff30f590.png)

**There are pieces of code left after making any changes and I have to close nvim to delete them.
use iterm2 console**

**Comment by ChristianChiarulli** [comment]
post your neovim version please.

**Comment by Blackbear78** [comment]
![Captura de Pantalla 2020-11-14 a la(s) 16 39 04](https://user-images.githubusercontent.com/74268641/99158401-0d013700-2698-11eb-91e5-01b3d91c0f02.png)

**Comment by ChristianChiarulli** [comment]
please open a new issue if issue is persisting.
