### ISSUE TITLE
React JS Code Doesn't get Commented with the appropriate comment string

### ISSUE THREAD

**Issue by ferran9908** [ChristianChiarulli/nvim#82]
<img width="1792" alt="Screenshot 2020-11-17 at 12 12 01 PM" src="https://user-images.githubusercontent.com/42429912/99355353-1aa00200-28ce-11eb-84f1-a00f2e690ee9.png">

I did some digging around the config and found that you've vim-context-commenstring to handle React commenting.

But for some reason, it doesn't work. 

Kudos to you for coming up with this config, btw.

**Comment by ChristianChiarulli** [comment]
yea, I just noticed this too. I definitely had this working at some point

**Comment by ChristianChiarulli** [comment]
```
autocmd! BufRead,BufNewFile *.{jsx,jx,js} setlocal filetype=javascript.jsx
autocmd FileType javascript.jsx setlocal commentstring={/*\ %s\ */}
```

^^ This should fix it

**Comment by ferran9908** [comment]
> ```
> autocmd! BufRead,BufNewFile *.{jsx,jx,js} setlocal filetype=javascript.jsx
> autocmd FileType javascript.jsx setlocal commentstring={/*\ %s\ */}
> ```
> 
> ^^ This should fix it

It works! Thanks!

**Comment by ChristianChiarulli** [comment]
🆒
