### ISSUE TITLE
Prettier isnt working on save in HTML format

### ISSUE THREAD

**Issue by tito600s** [ChristianChiarulli/nvim#88]
First of all thank you for all your effort. I'm trying to use your configuration as my replacement for VSCODE but I can't get it to acknowledge any errors that html files may have. I don't know if it's because of the coc-prettier or another plugin. But in css it shows me instantly that I have an error just like in js. Might you help me. Thank you.

**Comment by ChristianChiarulli** [comment]
CoC is no longer supported in favor of native LSP.
