### ISSUE TITLE
lua erro

### ISSUE THREAD

**Issue by yuetsao** [ChristianChiarulli/nvim#91]
no file '/Users/caoyue/.config/nvim/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-commentary/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-commentary/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-speeddating/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-speeddating/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-radical/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-radical/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-repeat/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-repeat/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/quick-scope/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/quick-scope/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-context-commentstring/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-context-commentstring/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-easymotion/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-easymotion/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-surround/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-surround/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-rooter/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-rooter/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-sleuth/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-sleuth/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/nvim-treesitter/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/nvim-treesitter/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/playground/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/playground/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/nvim-web-devicons/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/nvim-web-devicons/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-devicons/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-devicons/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/auto-pairs/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/auto-pairs/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-closetag/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/vim-closetag/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/nvcode-color-schemes.vim/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/nvcode-color-schemes.vim/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/coc.nvim/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/coc.nvim/lua/vim/treesitter/query/init.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/galaxyline.nvim/lua/vim/treesitter/query.lua'
        no file '/Users/caoyue/.config/nvim/autoload/plugged/galaxyline.nvim/lua/vim/treesitter/query/init.lua'

**Comment by NikarashiHatsu** [comment]
You need to install the latest nvim with a version from August 13 or newer.

**Comment by yuetsao** [comment]
thanks, I will try
