### ISSUE TITLE
Can't revert S key on command mode to default

### ISSUE THREAD

**Issue by vivi-et** [ChristianChiarulli/nvim#92]
Pressing s on command mode gives me a searchbox and not the default substitute-input mode.
I can't find settings related with s in mappings.vim. 
How could I revert s key to behave like default?

![vimSearchbox](https://user-images.githubusercontent.com/54794994/101397141-a88c6d00-390f-11eb-9a99-7d4f87fa3a49.png)

**Comment by ChristianChiarulli** [comment]
remove easymotion and the easymotion config file in `init.vim`
