### ISSUE TITLE
The directory mentioned in coc.vim is wrong

### ISSUE THREAD

**Issue by Athul-das7** [ChristianChiarulli/nvim#94]
The setup is pretty good yet you have forgot to put a proper path in coc-settings.json. /home/chris/.luabenvs/neovim4/bin/lua-lsp is the mentioned path but /home/USER/.luabenvs/neovim4/bin/lua-lsp . And for further notice the .luabenvs directory was not found in my terminal after running the single command installation. That could be the reason for the lua errors.
Hope it helps have a nice day :)

**Comment by spawmc** [comment]
thanks, I just had that problem, I'll try

**Comment by ChristianChiarulli** [comment]
I use sumnenko lua now with native LSP, CoC is no longer supported.
