### ISSUE TITLE
CocSearch not working

### ISSUE THREAD

**Issue by aniedzwiedz** [ChristianChiarulli/nvim#96]
CocSearch command itself is working fine, 
problem is with:
`nnoremap <leader>? CocSearch <C-R>=expand("<cword>")<CR><CR>`

> space + '?' ends up with cutting word and =expand("<cword>") in 'commands' 

![nvim_CocSearch](https://user-images.githubusercontent.com/34684295/102245398-cbb1b080-3efd-11eb-87e9-1c80ff787d80.gif)

**Comment by eddyekofo94** [comment]
Getting the same error @aniedzwiedz any solutions?

**Comment by ChristianChiarulli** [comment]
No more CoC. I recommend Telescope for searching.
