### ISSUE TITLE
how to do surround in vscode

### ISSUE THREAD

**Issue by relax2code** [ChristianChiarulli/nvim#99]
Hi, I can use surround in neovim by increase the delay but still not working in vscode , 
does anyone know why ?  or I'm missing something in vscode settings
Thank you

**Comment by markers16123** [comment]
I have the same problem.

**Comment by ChristianChiarulli** [comment]
Might have to make sure the plugin is actually loaded in vscode. I have if statements in a few places that will only load some plugins depending on if vscode is active or not.

**Comment by ChristianChiarulli** [comment]
removing surround for now unfortunately
